services:
  postgres:
    image: 'ankane/pgvector:v0.5.0'
    restart: always
    environment:
      - 'POSTGRES_DB=vector_store'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 15s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-tawfik@pgadmin.com}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}'
    volumes:
      - './servers.json:/pgadmin4/servers.json'
    ports:
      - '${PGADMIN_PORT:-5050}:80'